//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseinfoCalendar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AseCalendarEntities : DbContext
    {
        public AseCalendarEntities()
            : base("name=AseCalendarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dcs_documentos> dcs_documentos { get; set; }
        public virtual DbSet<dde_dependencia_de_etapas> dde_dependencia_de_etapas { get; set; }
        public virtual DbSet<etp_etapas> etp_etapas { get; set; }
        public virtual DbSet<pln_plan> pln_plan { get; set; }
    }
}
