//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseinfoCalendar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dcs_documentos
    {
        public int dcs_codigo { get; set; }
        public string dcs_nombre { get; set; }
        public string dcs_usuario_creacion { get; set; }
        public System.DateTime dcs_fecha_grabacion { get; set; }
        public string dcs_ruta { get; set; }
        public Nullable<int> etp_codigo { get; set; }
    
        public virtual etp_etapas etp_etapas { get; set; }
    }
}
