//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseinfoCalendar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dde_dependencia_de_etapas
    {
        public int dde_codigo { get; set; }
        public string dde_usuario_creacion { get; set; }
        public System.DateTime dde_fecha_creacion { get; set; }
        public int dde_etapa_principal { get; set; }
        public int dde_etapa_dependiente { get; set; }
    
        public virtual etp_etapas etp_etapas { get; set; }
        public virtual etp_etapas etp_etapas1 { get; set; }
    }
}
