//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseinfoCalendar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class etp_etapas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public etp_etapas()
        {
            this.dcs_documentos = new HashSet<dcs_documentos>();
            this.dde_dependencia_de_etapas = new HashSet<dde_dependencia_de_etapas>();
            this.dde_dependencia_de_etapas1 = new HashSet<dde_dependencia_de_etapas>();
            this.pls_planeacion_semanal = new HashSet<pls_planeacion_semanal>();
        }
    
        public int etp_codigo { get; set; }
        public string etp_nombre { get; set; }
        public int etp_orden { get; set; }
        public string etp_descripciom { get; set; }
        public string etp_objetivo { get; set; }
        public string etp_usuario_creacion { get; set; }
        public System.DateTime etp_fecha_grabacion { get; set; }
        public Nullable<int> pln_codigo { get; set; }
        public System.DateTime etp_fecha_inicio { get; set; }
        public System.DateTime etp_fecha_fin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dcs_documentos> dcs_documentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dde_dependencia_de_etapas> dde_dependencia_de_etapas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dde_dependencia_de_etapas> dde_dependencia_de_etapas1 { get; set; }
        public virtual pln_plan pln_plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pls_planeacion_semanal> pls_planeacion_semanal { get; set; }
    }
}
