//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseinfoCalendar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pln_plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pln_plan()
        {
            this.etp_etapas = new HashSet<etp_etapas>();
            this.pls_planeacion_semanal = new HashSet<pls_planeacion_semanal>();
        }
    
        public int pln_codigo { get; set; }
        public string pln_nombre { get; set; }
        public string pln_descripcion { get; set; }
        public string pln_objetivo { get; set; }
        public string pln_usuario_creacion { get; set; }
        public System.DateTime pln_fecha_creacion { get; set; }
        public string pln_codigo_visual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etp_etapas> etp_etapas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pls_planeacion_semanal> pls_planeacion_semanal { get; set; }
    }
}
