//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseinfoCalendar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pls_planeacion_semanal
    {
        public int pls_codigo { get; set; }
        public int pls_codpln { get; set; }
        public int pls_codetp { get; set; }
        public string pls_descripcion { get; set; }
        public System.DateTime pls_fecha { get; set; }
        public System.TimeSpan pls_hora_desde { get; set; }
        public System.TimeSpan pls_hora_hasta { get; set; }
        public string pls_usuario_creacion { get; set; }
        public System.DateTime pls_fecha_creacion { get; set; }
        public byte pls_cancelado { get; set; }
        public string pls_descripcion_cancelacion { get; set; }
    
        public virtual etp_etapas etp_etapas { get; set; }
        public virtual pln_plan pln_plan { get; set; }
    }
}
